" YanConfig Copyright (C) 2015 yanqd0@gmail.com
"
" This program comes with ABSOLUTELY NO WARRANTY under the terms of GPLv3.
" This is free software, and you are welcome to redistribute it under certain
" conditions; see the LISENSE in the root of this project.

set guifont=Monospace\ 12
set mouse=

" for markdown
set textwidth=1000

if &guioptions =~#'T'
    set guioptions-=T
    set guioptions-=m
    set guioptions-=r
    set guioptions-=L
endif

" function! LinuxToggleFullScreen()
"    call system("wmctrl -ir" . v:windowid . " -b toggle,fullscreen")
" endfun
" map <silent> <F11> <ESC>:call LinuxToggleFullScreen()<CR>
" map! <silent> <F11> <ESC>:call LinuxToggleFullScreen()<CR>
" map! <silent> <S-Insert> <C-r>+
