# YanConfig Copyright (C) 2015 yanqd0@gmail.com
#
# This program comes with ABSOLUTELY NO WARRANTY under the terms of GPLv3.
# This is free software, and you are welcome to redistribute it under certain
# conditions; see the LISENSE in the root of this project.

# export {
# ls
export CLICOLOR=1   #ls color
export CLICOLOR_FORCE=1
export LSCOLORS=gxfxaxdxcxegedabagacad  #ls color specific
# grep
export GREP_OPTIONS='--color=always'
export GREP_COLOR='5;40'
# }

# sub configs {
# Setting git completion
if [ -f ~/.bash/git-completion.bash ]; then
    . ~/.bash/git-completion.bash
fi

# functions
if [ -f ~/.bash/function.bash ]; then
    . ~/.bash/function.bash
fi

# alias
if [ -f ~/.bash/alias.bash ]; then
    . ~/.bash/alias.bash
fi
# }
